### ISSUE TITLE
求详细使用步骤

### ISSUE THREAD

**Issue by ztiandan** [cos120/captcha_crack#1]
如果要识别极验的验证码，项目介绍里面能给写个详细的操作步骤吗？不太会用这个项目，谢谢大神

**Comment by cos120** [comment]
极验这个底下的文字序列是白底黑字的，你需要先分割出这些文字，剩下的就是先yolo定位文字，再使用分类器就好了。麻烦的地方就是darknet的配置文件比较晦涩，我在知乎上写了一些详细的介绍。[地址](https://zhuanlan.zhihu.com/p/34186397)。
如果有问题我们还可以继续讨论😄

**Comment by mengpengfei** [comment]
极验的你打了多少样本啊，
