### ISSUE TITLE
训练3000次后预测不出来

### ISSUE THREAD

**Issue by zhazhami** [cos120/captcha_crack#11]
你好，我迭代大概3000次后，loss降到了2左右，但是发现什么都预测不出来，但是次数少的时候预测的概率都很低，这是为什么呢？

**Comment by cos120** [comment]
你这个预测是指`yolo`的预测么？提供一下详细的细节吧。

**Comment by zhazhami** [comment]
是的，我使用的yolov2，然后爬取了网易demo站的验证码：http://dun.163.com/trial/picture-click。
一共有500张，用的labal-img进行标记，然后cfg文件使用了yolo-origin.cfg，用训练集的图片作为测试集。
大概两千次迭代之前recall都是在提升，loss在降低的，但是预测的概率一直在降低，后来就趋近0了，并且预测的位置坐标会出现负数。
请问是我爬取的训练集图片不对吗？感觉爬的demo站上的图片混淆度都比较高。

**Comment by cos120** [comment]
你测试的时候用的是`yolo-origin.cfg`么，测试的时候应该把`batch size`调节为`1`，我测试的方法都是用`valid`得到一堆记事本文件，之后自己再切出来的。如果是训练过程中`darknet`自己进行的正确率预测我没有遇到过你说的准确率降低的情况，`recall`大致能到`0.9`，你的`label`可以上传一下看看。

**Comment by zhazhami** [comment]
好的非常感谢！我回去把batch size改下试试
