### ISSUE TITLE
能否提供极验文字识别训练集

### ISSUE THREAD

**Issue by Jiramew** [cos120/captcha_crack#2]
您好~
我直接用tensorflow构建fast-rcnn，可以标注文字位置，因为就这一类，效果不错。可是，想知道这些字是什么字还是需要大量样本训练。
另外，极验的左下角，有文字提示，也是需要训练的，目前用的crnn，效果不是很好，主要是验证码模仿的不太好。
求加qq详聊，2647724849。多谢~

**Comment by cos120** [comment]
极验那个文字我是框出来用机器标注的样本，没办法公开的。极验左下角那些字都是黑白的，你可以二值化了做分割再单字识别，用不到crnn这样预测文字行的方法。

**Comment by Jiramew** [comment]
啊，非常感谢您的回复~可能是我没有表述到位，不是yolo标框的训练集，是通过位置框切割下来的字以及它的label的训练集。或者您在训练yolo的时候就已经把每个字分类了（看您知乎上的，好像没有这么做）？左下脚的已经根据您说的修改了~
再次感谢~^0^

**Comment by cos120** [comment]
@Jiramew 训练集不能提供啊，我汉字的标注使用的[若快](http://www.ruokuai.com/)，网易那个大致3800多个字打个十万个样本就能达到99%的准确率了。

**Comment by Jiramew** [comment]
@cos120 嗯嗯，好哒。还是非常感谢您~^o^

**Comment by walink** [comment]
您好，能否提供下联系方法，有问题咨询您

**Comment by mengpengfei** [comment]
> @Jiramew 训练集不能提供啊，我汉字的标注使用的[若快](http://www.ruokuai.com/)，网易那个大致3800多个字打个十万个样本就能达到99%的准确率了。

极验的有多少字需要打多少样本？

**Comment by lilinna1990** [comment]
> @cos120 嗯嗯，好哒。还是非常感谢您~^o^

你好啊，请问后来有没有试验了，单文字的识别效果怎么样
