### ISSUE TITLE
目标文字还是需要自己识别把？

### ISSUE THREAD

**Issue by jerrypy** [cos120/captcha_crack#9]
看到crack里，需要传入sequence，所以目标文字还是需要自己识别？还有crack_by_post里：
```python
text1 = unicode(str(request.form['text']))
text = [text1[0], text1[1], text1[2]]
```
这默认只传入三个文字是debug代码？

**Comment by cos120** [comment]
因为文字是先进行定位扣下来后识别的，所以你可以知道哪个位置最有可能是什么字，再加上前端爬下来的字序列，就可以得到位置的序列了。那三个字是因为网易让点击的都是三个。
